modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="${mod_repo}/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${project.version}"
displayName="${mod_name}"
displayURL="${mod_repo}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="icon.png"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.18.2]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="botania"
mandatory=true
versionRange="${botania_dependency}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="theoneprobe"
mandatory=true
versionRange="${top_dependency}"
ordering="NONE"
side="BOTH"